/**
 * ENS Registry for Clear Signing Specs
 *
 * Uses text records on `veryclear.eth` as a verifiable on-chain registry.
 * Each text record maps a contract address to a spec identifier:
 *
 *   key:   "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
 *   value: '{"specName":"ERC20","type":"token","decimals":6,"symbol":"USDC"}'
 *
 * The spec identifier is used to load the full spec JSON from static assets
 * (generated by the Verity compiler). The ENS record proves which spec the
 * Verity team has approved for a given contract address.
 */

import { ethers } from "ethers";

export const ENS_NAME = "veryclear.eth";
const MAINNET_RPC = "https://ethereum-rpc.publicnode.com";

/**
 * ENS text record format for a registered contract.
 *
 * - spec: name of the compiled spec (matches a JSON file in /public/specs/)
 * - deploy: per-address overrides (symbol, decimals differ per deployment
 *   of the same spec, e.g. USDC vs USDT both use ERC20 spec)
 * - circuits: SHA-256 hashes of verification keys, keyed by function name,
 *   pinning the exact circuits compiled from this spec
 */
export type EnsSpecEntry = {
  spec: string;
  deploy?: {
    symbol?: string;
    decimals?: number;
  };
  circuits?: Record<string, string>;
};

// ─── Internals ──────────────────────────────────────────────────────────────

/**
 * Resolve the ENS resolver address for veryclear.eth from mainnet.
 * Always queries mainnet regardless of the wallet's chain.
 */
async function getResolverAddress(): Promise<string | null> {
  try {
    const provider = new ethers.JsonRpcProvider(MAINNET_RPC);
    console.log("[ENS] Querying resolver for", ENS_NAME, "via", MAINNET_RPC);
    const resolver = await provider.getResolver(ENS_NAME);
    if (!resolver) {
      console.log("[ENS] No resolver found for", ENS_NAME);
      return null;
    }
    console.log("[ENS] Resolver address:", resolver.address);
    return resolver.address;
  } catch (e) {
    console.error("[ENS] Failed to get resolver:", e);
    return null;
  }
}

// ─── Read (public, no wallet needed) ────────────────────────────────────────

/**
 * Read a spec entry from the ENS registry.
 *
 * @param contractAddress - The contract address to look up
 * @returns The spec entry, or null if not registered
 */
export async function readSpecFromEns(
  contractAddress: string
): Promise<EnsSpecEntry | null> {
  try {
    const provider = new ethers.JsonRpcProvider(MAINNET_RPC);
    const resolver = await provider.getResolver(ENS_NAME);
    if (!resolver) {
      console.log("[ENS] No resolver, skipping read for", contractAddress);
      return null;
    }

    const key = contractAddress.toLowerCase();
    console.log("[ENS] Reading text record:", key);
    const value = await resolver.getText(key);
    if (!value) {
      console.log("[ENS] No text record for", key);
      return null;
    }

    console.log("[ENS] Found:", value);
    return JSON.parse(value) as EnsSpecEntry;
  } catch (e) {
    console.error("[ENS] Read error:", e);
    return null;
  }
}

// ─── Write (requires wallet on mainnet) ─────────────────────────────────────

/**
 * Get a signer from the browser wallet (MetaMask etc.)
 */
export async function connectWallet(): Promise<ethers.BrowserProvider> {
  if (typeof window === "undefined" || !window.ethereum) {
    throw new Error("No wallet detected. Please install MetaMask.");
  }
  const provider = new ethers.BrowserProvider(window.ethereum);
  await provider.send("eth_requestAccounts", []);
  return provider;
}

/**
 * Set a spec entry in the ENS registry.
 *
 * Resolves veryclear.eth via a mainnet RPC to find the resolver contract,
 * then sends the setText transaction through the user's wallet.
 *
 * @param provider - Connected browser provider with signer
 * @param contractAddress - The contract address to register
 * @param entry - The spec metadata to store
 * @returns Transaction hash
 */
export async function writeSpecToEns(
  provider: ethers.BrowserProvider,
  contractAddress: string,
  entry: EnsSpecEntry
): Promise<string> {
  const signer = await provider.getSigner();
  const signerAddr = await signer.getAddress();
  const network = await provider.getNetwork();
  console.log("[ENS] Write: signer =", signerAddr, "chainId =", network.chainId.toString());

  // Check chain
  if (network.chainId !== 1n) {
    throw new Error(
      `Please switch to Ethereum Mainnet (current chain: ${network.chainId}). ` +
      `ENS text records for ${ENS_NAME} live on mainnet.`
    );
  }

  // Get resolver address from mainnet RPC (reliable, doesn't depend on wallet's ENS support)
  const resolverAddress = await getResolverAddress();
  if (!resolverAddress) {
    throw new Error(
      `No resolver found for ${ENS_NAME}. ` +
      `Make sure the ENS name is registered and has a resolver set.`
    );
  }

  console.log("[ENS] Using resolver at", resolverAddress);

  const resolverAbi = [
    "function setText(bytes32 node, string key, string value) external",
  ];
  const resolverContract = new ethers.Contract(
    resolverAddress,
    resolverAbi,
    signer
  );

  const node = ethers.namehash(ENS_NAME);
  const key = contractAddress.toLowerCase();
  const value = JSON.stringify(entry);

  console.log("[ENS] setText:", { node, key, value: value.slice(0, 50) + "..." });

  const tx = await resolverContract.setText(node, key, value);
  console.log("[ENS] TX sent:", tx.hash);
  await tx.wait();
  console.log("[ENS] TX confirmed:", tx.hash);

  return tx.hash;
}

/**
 * Remove a spec entry from the ENS registry.
 */
export async function removeSpecFromEns(
  provider: ethers.BrowserProvider,
  contractAddress: string
): Promise<string> {
  const signer = await provider.getSigner();
  const network = await provider.getNetwork();

  if (network.chainId !== 1n) {
    throw new Error(`Please switch to Ethereum Mainnet (current chain: ${network.chainId}).`);
  }

  const resolverAddress = await getResolverAddress();
  if (!resolverAddress) {
    throw new Error(`No resolver found for ${ENS_NAME}.`);
  }

  const resolverAbi = [
    "function setText(bytes32 node, string key, string value) external",
  ];
  const resolverContract = new ethers.Contract(
    resolverAddress,
    resolverAbi,
    signer
  );

  const node = ethers.namehash(ENS_NAME);
  const key = contractAddress.toLowerCase();

  const tx = await resolverContract.setText(node, key, "");
  await tx.wait();

  return tx.hash;
}
