/**
 * ENS Registry for Clear Signing Specs
 *
 * Uses text records on `veryclear.eth` as a verifiable on-chain registry.
 * Each text record maps a contract address to a spec identifier:
 *
 *   key:   "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48"
 *   value: '{"specName":"ERC20","type":"token","decimals":6,"symbol":"USDC"}'
 *
 * The spec identifier is used to load the full spec JSON from static assets
 * (generated by the Verity compiler). The ENS record proves which spec the
 * Verity team has approved for a given contract address.
 */

import { ethers } from "ethers";

export const ENS_NAME = "veryclear.eth";

/** Metadata stored in ENS for each registered contract. */
export type EnsSpecEntry = {
  specName: string;
  type: "token" | "protocol" | "contract" | "ens";
  decimals?: number;
  symbol?: string;
};

// ─── Read (public, no wallet needed) ────────────────────────────────────────

/**
 * Read a spec entry from the ENS registry.
 *
 * @param contractAddress - The contract address to look up
 * @param rpcUrl - Ethereum RPC URL (defaults to public Cloudflare)
 * @returns The spec entry, or null if not registered
 */
export async function readSpecFromEns(
  contractAddress: string,
  rpcUrl: string = "https://cloudflare-eth.com"
): Promise<EnsSpecEntry | null> {
  try {
    const provider = new ethers.JsonRpcProvider(rpcUrl);
    const resolver = await provider.getResolver(ENS_NAME);
    if (!resolver) return null;

    const key = contractAddress.toLowerCase();
    const value = await resolver.getText(key);
    if (!value) return null;

    return JSON.parse(value) as EnsSpecEntry;
  } catch {
    return null;
  }
}

/**
 * Read all known spec entries from ENS.
 * Queries a predefined list of contract addresses.
 */
export async function readAllSpecsFromEns(
  contractAddresses: string[],
  rpcUrl?: string
): Promise<Map<string, EnsSpecEntry>> {
  const results = new Map<string, EnsSpecEntry>();
  const promises = contractAddresses.map(async (addr) => {
    const entry = await readSpecFromEns(addr, rpcUrl);
    if (entry) results.set(addr.toLowerCase(), entry);
  });
  await Promise.all(promises);
  return results;
}

// ─── Write (requires wallet) ────────────────────────────────────────────────

/**
 * Get a signer from the browser wallet (MetaMask etc.)
 */
export async function connectWallet(): Promise<ethers.BrowserProvider> {
  if (typeof window === "undefined" || !window.ethereum) {
    throw new Error("No wallet detected. Please install MetaMask.");
  }
  const provider = new ethers.BrowserProvider(window.ethereum);
  await provider.send("eth_requestAccounts", []);
  return provider;
}

/**
 * Set a spec entry in the ENS registry.
 *
 * Sends a setText transaction on the resolver for veryclear.eth.
 * The caller must be the owner/manager of the ENS name.
 *
 * @param provider - Connected browser provider with signer
 * @param contractAddress - The contract address to register
 * @param entry - The spec metadata to store
 * @returns Transaction hash
 */
export async function writeSpecToEns(
  provider: ethers.BrowserProvider,
  contractAddress: string,
  entry: EnsSpecEntry
): Promise<string> {
  const signer = await provider.getSigner();
  const resolver = await provider.getResolver(ENS_NAME);
  if (!resolver) {
    throw new Error(`No resolver found for ${ENS_NAME}`);
  }

  // Get the resolver contract with signer
  const resolverAddress = resolver.address;
  const resolverAbi = [
    "function setText(bytes32 node, string key, string value) external",
  ];
  const resolverContract = new ethers.Contract(
    resolverAddress,
    resolverAbi,
    signer
  );

  const node = ethers.namehash(ENS_NAME);
  const key = contractAddress.toLowerCase();
  const value = JSON.stringify(entry);

  const tx = await resolverContract.setText(node, key, value);
  await tx.wait();

  return tx.hash;
}

/**
 * Remove a spec entry from the ENS registry.
 */
export async function removeSpecFromEns(
  provider: ethers.BrowserProvider,
  contractAddress: string
): Promise<string> {
  const signer = await provider.getSigner();
  const resolver = await provider.getResolver(ENS_NAME);
  if (!resolver) {
    throw new Error(`No resolver found for ${ENS_NAME}`);
  }

  const resolverAddress = resolver.address;
  const resolverAbi = [
    "function setText(bytes32 node, string key, string value) external",
  ];
  const resolverContract = new ethers.Contract(
    resolverAddress,
    resolverAbi,
    signer
  );

  const node = ethers.namehash(ENS_NAME);
  const key = contractAddress.toLowerCase();

  const tx = await resolverContract.setText(node, key, "");
  await tx.wait();

  return tx.hash;
}
