/**
 * Intent Spec Loader
 *
 * Loads IntentSpec JSON files generated by the Verity compiler's
 * ExportIntentJson.lean script and converts them to the frontend types.
 *
 * The JSON files live in /public/specs/ and are produced by:
 *   lake env lean --run Compiler/ExportIntentJson.lean
 *
 * This ensures the frontend specs always match the Lean source of truth
 * in verity/Contracts/<name>/Display.lean.
 */

import type {
  IntentSpec,
  IntentFn,
  Binding,
  Stmt,
  Expr,
  Template,
  Hole,
  Format,
  ParamType,
} from "./types";

// ─── JSON Types (raw compiler output) ───────────────────────────────────────

/* eslint-disable @typescript-eslint/no-explicit-any */
type JsonExpr = any;
type JsonStmt = any;
type JsonSpec = {
  contractName: string;
  fns: {
    name: string;
    params: { name: string; type: string }[];
    returnKind: string;
    body: JsonStmt[];
    expr: JsonExpr | null;
  }[];
  constants: { name: string; value: JsonExpr }[];
  bindings: {
    functionName: string;
    intentFnName: string;
    selector?: string;
    abiSignature?: string;
    paramMapping?: string[];
  }[];
};
/* eslint-enable @typescript-eslint/no-explicit-any */

// ─── Converters ─────────────────────────────────────────────────────────────

function parseFormat(
  f: { kind: string; decimals?: number; symbol?: string; enumName?: string },
  deploymentMeta?: { decimals?: number; symbol?: string }
): Format {
  switch (f.kind) {
    case "tokenAmount":
      // Deployment decimals/symbol override the generic spec values
      // (e.g. ERC-20 spec says 18 decimals, but USDC deployment has 6)
      return {
        kind: "tokenAmount",
        decimals: deploymentMeta?.decimals ?? f.decimals ?? 18,
        symbol: deploymentMeta?.symbol ?? f.symbol,
      };
    case "address":
      return { kind: "address" };
    case "enum":
      return { kind: "raw" };
    default:
      return { kind: "raw" };
  }
}

function parseHole(
  h: { name: string; format: { kind: string; decimals?: number; symbol?: string } },
  deploymentMeta?: { decimals?: number; symbol?: string }
): Hole {
  return { name: h.name, format: parseFormat(h.format, deploymentMeta) };
}

function parseTemplate(
  t: { text: string; holes: { name: string; format: any }[] },
  deploymentMeta?: { decimals?: number; symbol?: string }
): Template {
  return { text: t.text, holes: t.holes.map(h => parseHole(h, deploymentMeta)) };
}

function parseExpr(e: JsonExpr): Expr {
  switch (e.kind) {
    case "param":
      return { kind: "param", name: e.name };
    case "const":
      return { kind: "const", value: BigInt(e.value) };
    case "eq":
      return { kind: "eq", left: parseExpr(e.left), right: parseExpr(e.right) };
    case "call":
      // Inline function calls: for isMaxUint(amount), we expand to eq(amount, MAX)
      // This is handled by the evaluator which resolves calls
      return { kind: "eq", left: parseExpr(e.args[0]), right: { kind: "const", value: 0n } };
    default:
      return { kind: "const", value: 0n };
  }
}

function parseStmt(s: JsonStmt): Stmt {
  switch (s.kind) {
    case "emit":
      return { kind: "emit", template: parseTemplate(s.template) };
    case "when":
      return {
        kind: "when",
        condition: parseCondition(s.condition),
        then: s.then.map(parseStmt),
        otherwise: s.otherwise.map(parseStmt),
      };
    default:
      // Skip unsupported statements
      return { kind: "emit", template: { text: "(unsupported)", holes: [] } };
  }
}

/**
 * Parse a condition expression, resolving predicate calls.
 *
 * The Lean compiler outputs conditions like:
 *   { kind: "call", name: "isMaxUint", args: [{ kind: "param", name: "amount" }] }
 *
 * We need to resolve this to the actual expression by looking up the predicate
 * and substituting the argument.
 */
function parseCondition(e: JsonExpr): Expr {
  if (e.kind === "call") {
    // For now, we return a placeholder. The actual resolution happens
    // in resolvePredicates() after all functions are parsed.
    return { kind: "eq", left: parseExpr(e.args[0]), right: { kind: "const", value: 0n } };
  }
  return parseExpr(e);
}

function parseParamType(t: string): ParamType {
  if (t.startsWith("array(")) return "address[]"; // Simplified
  switch (t) {
    case "uint256": return "uint256";
    case "address": return "address";
    case "bool": return "bool";
    default: return "uint256";
  }
}

/**
 * Load a compiler-generated intent spec JSON and convert to frontend types.
 *
 * @param json - The raw JSON from the Verity compiler
 * @param address - Contract address (not in the Lean spec, added per-deployment)
 * @param entry - ENS registry entry with deploy overrides
 */
export function loadIntentSpec(
  json: JsonSpec,
  address: string,
  entry: { spec: string; deploy?: { symbol?: string; decimals?: number }; circuits?: Record<string, string> }
): IntentSpec {
  const meta = entry.deploy;
  // First, extract constant values for predicate resolution
  const constantValues = new Map<string, bigint>();
  for (const c of json.constants) {
    if (c.value.kind === "const") {
      constantValues.set(c.name, BigInt(c.value.value));
    }
  }

  // Find predicate functions (returnKind === "bool" with an expr body)
  const predicates = new Map<string, { params: string[]; expr: JsonExpr }>();
  for (const fn of json.fns) {
    if (fn.returnKind === "bool" && fn.expr) {
      predicates.set(fn.name, {
        params: fn.params.map(p => p.name),
        expr: fn.expr,
      });
    }
  }

  // Parse intent functions (returnKind === "void" with a body)
  const fns: IntentFn[] = json.fns
    .filter(fn => fn.returnKind === "void" && fn.body.length > 0)
    .map(fn => ({
      name: fn.name,
      params: fn.params.map(p => ({ name: p.name, type: parseParamType(p.type) })),
      body: fn.body.map(s => resolveStmt(s, predicates, constantValues, meta)),
    }));

  // Parse bindings
  const bindings: Binding[] = json.bindings
    .filter(b => b.selector) // Only include bindings that have selectors
    .map(b => ({
      selector: b.selector!,
      abiSignature: b.abiSignature ?? b.functionName,
      intentFnName: b.intentFnName,
      paramMapping: b.paramMapping ?? [],
    }));

  return {
    contractName: json.contractName,
    address,
    deploy: meta ? { symbol: meta.symbol, decimals: meta.decimals } : undefined,
    constants: Object.fromEntries(constantValues),
    fns,
    bindings,
  };
}

/**
 * Resolve predicate calls in statements to actual expressions.
 *
 * Transforms:  call("isMaxUint", [param("amount")])
 * Into:        eq(param("amount"), const(MAX_UINT256))
 */
function resolveStmt(
  s: JsonStmt,
  predicates: Map<string, { params: string[]; expr: JsonExpr }>,
  constants: Map<string, bigint>,
  deploymentMeta?: { decimals?: number; symbol?: string }
): Stmt {
  if (s.kind === "emit") {
    return { kind: "emit", template: parseTemplate(s.template, deploymentMeta) };
  }
  if (s.kind === "when") {
    return {
      kind: "when",
      condition: resolveExpr(s.condition, predicates, constants),
      then: s.then.map((st: JsonStmt) => resolveStmt(st, predicates, constants, deploymentMeta)),
      otherwise: s.otherwise.map((st: JsonStmt) => resolveStmt(st, predicates, constants, deploymentMeta)),
    };
  }
  return { kind: "emit", template: { text: "(unsupported)", holes: [] } };
}

/**
 * Resolve an expression, expanding predicate calls and constant references.
 */
function resolveExpr(
  e: JsonExpr,
  predicates: Map<string, { params: string[]; expr: JsonExpr }>,
  constants: Map<string, bigint>
): Expr {
  if (e.kind === "call" && predicates.has(e.name)) {
    // Expand predicate: substitute params and resolve recursively
    const pred = predicates.get(e.name)!;
    const substituted = substituteParams(pred.expr, pred.params, e.args);
    return resolveExpr(substituted, predicates, constants);
  }
  if (e.kind === "param") {
    // Check if it's a constant reference
    const constVal = constants.get(e.name);
    if (constVal !== undefined) {
      return { kind: "const", value: constVal };
    }
    return { kind: "param", name: e.name };
  }
  if (e.kind === "eq") {
    return {
      kind: "eq",
      left: resolveExpr(e.left, predicates, constants),
      right: resolveExpr(e.right, predicates, constants),
    };
  }
  if (e.kind === "const") {
    return { kind: "const", value: BigInt(e.value) };
  }
  return { kind: "const", value: 0n };
}

/**
 * Substitute parameter references in an expression with actual arguments.
 */
function substituteParams(
  expr: JsonExpr,
  paramNames: string[],
  args: JsonExpr[]
): JsonExpr {
  if (expr.kind === "param") {
    const idx = paramNames.indexOf(expr.name);
    if (idx >= 0 && idx < args.length) {
      return args[idx];
    }
    return expr;
  }
  if (expr.kind === "eq" || expr.kind === "ne" || expr.kind === "lt" ||
      expr.kind === "gt" || expr.kind === "le" || expr.kind === "ge") {
    return {
      ...expr,
      left: substituteParams(expr.left, paramNames, args),
      right: substituteParams(expr.right, paramNames, args),
    };
  }
  return expr;
}
