/**
 * Intent Specification Registry
 *
 * Specs are resolved from two sources:
 * 1. ENS registry (veryclear.eth) — on-chain source of truth
 * 2. Static fallback — bundled compiler output for offline use
 *
 * The ENS registry maps contract addresses to spec identifiers
 * (specName, type, decimals, symbol). The spec AST is loaded from
 * static JSON files generated by the Verity compiler.
 */

import type { IntentSpec } from "./types";
import { loadIntentSpec } from "./loader";
import { readSpecFromEns, type EnsSpecEntry } from "./ens";
import ERC20_INTENT_JSON from "../../../../public/specs/ERC20.intent.json";
import UNISWAP_V2_INTENT_JSON from "../../../../public/specs/UniswapV2.intent.json";

// ─── Spec JSON index (keyed by specName from ENS) ───────────────────────────

/* eslint-disable @typescript-eslint/no-explicit-any */
const SPEC_JSONS: Record<string, any> = {
  ERC20: ERC20_INTENT_JSON,
  UniswapV2Router: UNISWAP_V2_INTENT_JSON,
};
/* eslint-enable @typescript-eslint/no-explicit-any */

// ─── Static fallback registry ───────────────────────────────────────────────

const STATIC_SPECS: Record<string, IntentSpec> = {};

function registerStatic(address: string, specName: string, meta: EnsSpecEntry) {
  const json = SPEC_JSONS[specName];
  if (!json) return;
  STATIC_SPECS[address.toLowerCase()] = loadIntentSpec(json, address, meta);
}

// Pre-register known contracts as fallback
registerStatic("0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48", "ERC20", {
  specName: "ERC20", type: "token", decimals: 6, symbol: "USDC",
});
registerStatic("0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D", "UniswapV2Router", {
  specName: "UniswapV2Router", type: "protocol",
});

// Address-only specs for display resolution
STATIC_SPECS["0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"] = {
  contractName: "WETH",
  address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
  type: "token",
  decimals: 18,
  symbol: "WETH",
  constants: {},
  fns: [],
  bindings: [],
};

export const SPECS = STATIC_SPECS;

// ─── ENS-aware lookup ───────────────────────────────────────────────────────

/**
 * Find a spec by contract address.
 * Tries ENS first (veryclear.eth), falls back to static registry.
 */
export async function findSpecFromEns(
  contractAddress: string
): Promise<IntentSpec | null> {
  // Try ENS
  const ensEntry = await readSpecFromEns(contractAddress);
  if (ensEntry) {
    const json = SPEC_JSONS[ensEntry.specName];
    if (json) {
      return loadIntentSpec(json, contractAddress, ensEntry);
    }
  }

  // Fall back to static
  return STATIC_SPECS[contractAddress.toLowerCase()] ?? null;
}

/** Synchronous fallback (for non-async contexts). */
export function findSpec(contractAddress: string): IntentSpec | null {
  return STATIC_SPECS[contractAddress.toLowerCase()] ?? null;
}
