/**
 * Intent Specification Registry
 *
 * ERC-20 spec is loaded from the Verity compiler output (public/specs/ERC20.intent.json),
 * generated by: lake env lean --run Compiler/ExportIntentJson.lean
 * Source of truth: verity/Contracts/ERC20/Display.lean
 *
 * Uniswap V2 spec is defined here because it's not yet in Verity.
 * Address-only specs (WETH, vitalik.eth) provide display metadata for address resolution.
 */

import type { IntentSpec } from "./types";
import { loadIntentSpec } from "./loader";
import ERC20_INTENT_JSON from "../../../../public/specs/ERC20.intent.json";

// ─── USDC (ERC-20) — loaded from Verity compiler output ─────────────────────

/**
 * USDC intent spec, loaded from the Lean compiler JSON.
 *
 * The JSON was generated from verity/Contracts/ERC20/Display.lean:
 *   intent_spec "ERC20" where
 *     const MAX_UINT256 := (2^256 - 1)
 *     predicate isMaxUint(v : uint256) := v == MAX_UINT256
 *     intent transfer(to : address, amount : uint256) where ...
 *     intent approve(spender : address, amount : uint256) where ...
 *     intent transferFrom(fromAddr : address, to : address, amount : uint256) where ...
 */
export const USDC_SPEC: IntentSpec = loadIntentSpec(
  ERC20_INTENT_JSON,
  "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
  { type: "token", decimals: 6, symbol: "USDC" }
);

// ─── Uniswap V2 Router (not yet in Verity) ──────────────────────────────────

export const UNISWAP_V2_SPEC: IntentSpec = {
  contractName: "Uniswap V2 Router",
  address: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D",
  type: "protocol",
  constants: {},
  fns: [
    {
      name: "swapExactTokensForTokens",
      params: [
        { name: "amountIn", type: "uint256" },
        { name: "amountOutMin", type: "uint256" },
        { name: "path", type: "address[]" },
        { name: "to", type: "address" },
        { name: "deadline", type: "uint256" },
      ],
      body: [
        {
          kind: "emit",
          template: {
            text: "Swap {amountIn} {tokenIn} for at least {amountOutMin} {tokenOut}, send to {to}",
            holes: [
              { name: "amountIn", format: { kind: "tokenAmount", decimals: 18 } },
              { name: "tokenIn", format: { kind: "address" } },
              { name: "amountOutMin", format: { kind: "tokenAmount", decimals: 6 } },
              { name: "tokenOut", format: { kind: "address" } },
              { name: "to", format: { kind: "address" } },
            ],
          },
        },
      ],
    },
  ],
  bindings: [
    {
      selector: "0x38ed1739",
      abiSignature: "swapExactTokensForTokens(uint256,uint256,address[],address,uint256)",
      intentFnName: "swapExactTokensForTokens",
      paramMapping: ["amountIn", "amountOutMin", "path", "to", "deadline"],
    },
  ],
};

// ─── Address-only specs (display metadata for resolution) ────────────────────

export const WETH_SPEC: IntentSpec = {
  contractName: "WETH",
  address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
  type: "token",
  decimals: 18,
  symbol: "WETH",
  constants: {},
  fns: [],
  bindings: [],
};

export const VITALIK_SPEC: IntentSpec = {
  contractName: "vitalik.eth",
  address: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
  type: "ens",
  constants: {},
  fns: [],
  bindings: [],
};

// ─── Registry ────────────────────────────────────────────────────────────────

export const SPECS: Record<string, IntentSpec> = {
  [USDC_SPEC.address.toLowerCase()]: USDC_SPEC,
  [UNISWAP_V2_SPEC.address.toLowerCase()]: UNISWAP_V2_SPEC,
  [WETH_SPEC.address.toLowerCase()]: WETH_SPEC,
  [VITALIK_SPEC.address.toLowerCase()]: VITALIK_SPEC,
};

export function findSpec(contractAddress: string): IntentSpec | null {
  return SPECS[contractAddress.toLowerCase()] ?? null;
}
