/**
 * Intent Specification Registry
 *
 * ERC-20 spec is loaded from the Verity compiler output (public/specs/ERC20.intent.json),
 * generated by: lake env lean --run Compiler/ExportIntentJson.lean
 * Source of truth: verity/Contracts/ERC20/Display.lean
 *
 * Uniswap V2 spec is defined here because it's not yet in Verity.
 * Address-only specs (WETH, vitalik.eth) provide display metadata for address resolution.
 */

import type { IntentSpec } from "./types";
import { loadIntentSpec } from "./loader";
import ERC20_INTENT_JSON from "../../../../public/specs/ERC20.intent.json";
import UNISWAP_V2_INTENT_JSON from "../../../../public/specs/UniswapV2.intent.json";

// ─── USDC (ERC-20) — from verity/Contracts/ERC20/Display.lean ────────────────

export const USDC_SPEC: IntentSpec = loadIntentSpec(
  ERC20_INTENT_JSON,
  "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
  { type: "token", decimals: 6, symbol: "USDC" }
);

// ─── Uniswap V2 Router — from verity/Contracts/UniswapV2/Display.lean ────────

export const UNISWAP_V2_SPEC: IntentSpec = loadIntentSpec(
  UNISWAP_V2_INTENT_JSON,
  "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D",
  { type: "protocol" }
);

// ─── Address-only specs (display metadata for resolution) ────────────────────

export const WETH_SPEC: IntentSpec = {
  contractName: "WETH",
  address: "0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2",
  type: "token",
  decimals: 18,
  symbol: "WETH",
  constants: {},
  fns: [],
  bindings: [],
};

export const VITALIK_SPEC: IntentSpec = {
  contractName: "vitalik.eth",
  address: "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
  type: "ens",
  constants: {},
  fns: [],
  bindings: [],
};

// ─── Registry ────────────────────────────────────────────────────────────────

export const SPECS: Record<string, IntentSpec> = {
  [USDC_SPEC.address.toLowerCase()]: USDC_SPEC,
  [UNISWAP_V2_SPEC.address.toLowerCase()]: UNISWAP_V2_SPEC,
  [WETH_SPEC.address.toLowerCase()]: WETH_SPEC,
  [VITALIK_SPEC.address.toLowerCase()]: VITALIK_SPEC,
};

export function findSpec(contractAddress: string): IntentSpec | null {
  return SPECS[contractAddress.toLowerCase()] ?? null;
}
