export default function WhatIsAFormalProof() {
  return (
    <main className="font-serif max-w-[680px] mx-auto px-6 py-20 md:py-32">
      <header className="mb-20">
        <h1 className="text-3xl md:text-4xl font-semibold tracking-tight leading-tight">
          What is a formal proof?
        </h1>
        <p className="mt-3 text-secondary text-base">
          A short explanation for non-specialists
        </p>
      </header>

      <section className="mb-16 leading-relaxed space-y-4">
        <p>
          A formal proof is a program that a computer can check. It does not
          rely on human judgment: either the proof is accepted by the checker,
          or it is rejected. There is no middle ground.
        </p>
        <p>
          Think of it this way: a regular test checks that a program works for
          a few examples. A formal proof checks that it works for{" "}
          <em>every possible input</em>.
        </p>
      </section>

      <section className="mb-16">
        <h2 className="text-lg font-semibold tracking-tight mb-4">
          A simple example
        </h2>
        <p className="leading-relaxed mb-6">
          Suppose we write a function that inserts a number into a sorted list.
          We want to prove that the result is still sorted. Here is what that
          looks like in Lean 4:
        </p>

        <div className="bg-[#1e1e2e] rounded-lg px-6 py-5 overflow-x-auto text-[13.5px] leading-[1.7] font-mono">
          <div>
            <span className="text-[#cba6f7]">def</span>{" "}
            <span className="text-[#89b4fa]">insert</span>{" "}
            <span className="text-[#cdd6f4]">(x : Nat) : List Nat → List Nat</span>
          </div>
          <div>
            {"  "}| <span className="text-[#cdd6f4]">[]</span>{" "}
            <span className="text-[#89dceb]">=&gt;</span>{" "}
            <span className="text-[#cdd6f4]">[x]</span>
          </div>
          <div>
            {"  "}| <span className="text-[#cdd6f4]">h :: t</span>{" "}
            <span className="text-[#89dceb]">=&gt;</span>
          </div>
          <div>
            {"    "}<span className="text-[#cba6f7]">if</span>{" "}
            <span className="text-[#cdd6f4]">x ≤ h</span>{" "}
            <span className="text-[#cba6f7]">then</span>{" "}
            <span className="text-[#cdd6f4]">x :: h :: t</span>
          </div>
          <div>
            {"    "}<span className="text-[#cba6f7]">else</span>{" "}
            <span className="text-[#cdd6f4]">h :: insert x t</span>
          </div>
        </div>

        <p className="leading-relaxed mt-6 mb-6 text-secondary text-[15px]">
          This inserts a number into the right position. If the number is
          smaller than the head, it goes first. Otherwise, it recurses.
        </p>

        <p className="leading-relaxed mb-6">
          Now we state what we want to prove: that inserting into a sorted
          list produces a sorted list.
        </p>

        <div className="bg-[#1e1e2e] rounded-lg px-6 py-5 overflow-x-auto text-[13.5px] leading-[1.7] font-mono">
          <div className="text-[#6c7086]">
            -- &quot;For any number x and any sorted list l,
          </div>
          <div className="text-[#6c7086]">
            --  insert x l is also sorted.&quot;
          </div>
          <div className="mt-2">
            <span className="text-[#cba6f7]">theorem</span>{" "}
            <span className="text-[#a6e3a1]">insert_sorted</span>
          </div>
          <div>
            {"  "}<span className="text-[#cdd6f4]">(x : Nat) (l : List Nat)</span>
          </div>
          <div>
            {"  "}<span className="text-[#cdd6f4]">(h : Sorted l)</span>{" "}
            <span className="text-[#89dceb]">:</span>{" "}
            <span className="text-[#f9e2af]">Sorted (insert x l)</span>
          </div>
        </div>

        <p className="leading-relaxed mt-6 text-secondary text-[15px]">
          The <span className="font-mono text-[13px]">theorem</span> keyword
          tells Lean: &ldquo;I claim this is true, and here is my proof.&rdquo;
          If the proof has any gap or error, Lean refuses to compile.
        </p>
      </section>

      <section className="mb-16">
        <h2 className="text-lg font-semibold tracking-tight mb-4">
          How does the checking work?
        </h2>
        <div className="leading-relaxed space-y-4">
          <p>
            Lean has a small, well-audited <em>kernel</em> (about 5,000 lines
            of code) that accepts or rejects proofs. Every proof, no matter
            how complex, must pass through this kernel.
          </p>
          <p>
            The kernel does not care how the proof was found. It could have
            been written by a human, generated by an AI, or produced by an
            automated solver. What matters is that each logical step is valid.
          </p>
          <p className="font-medium">
            If the proof compiles, it is correct. If it doesn&apos;t, it
            isn&apos;t.
          </p>
        </div>
      </section>

      <section className="mb-16">
        <h2 className="text-lg font-semibold tracking-tight mb-4">
          Tests vs. formal proofs
        </h2>
        <div className="border border-border rounded px-6 py-5 leading-relaxed">
          <p className="mb-4">
            <strong className="font-medium">A test</strong> says: &ldquo;I
            tried inserting 3 into [1, 2, 4] and the result was sorted.&rdquo;
          </p>
          <p>
            <strong className="font-medium">A formal proof</strong> says:
            &ldquo;For <em>every</em> number and <em>every</em> sorted list,
            insertion preserves sorting.&rdquo;
          </p>
        </div>
      </section>

      <section className="mb-16">
        <h2 className="text-lg font-semibold tracking-tight mb-4">
          Why does this matter for smart contracts?
        </h2>
        <div className="leading-relaxed space-y-4">
          <p>
            Smart contracts handle real money. A bug in the arithmetic of a
            DeFi protocol can drain millions. Tests catch some bugs, audits
            catch more, but neither can guarantee correctness for all possible
            states.
          </p>
          <p>
            A formal proof can. It is a mathematical certificate that the
            property holds in every case, not just the ones the auditor
            thought to check.
          </p>
        </div>
      </section>

      <section className="mb-16">
        <h2 className="text-lg font-semibold tracking-tight mb-6">
          See it in practice
        </h2>
        <p className="leading-relaxed">
          <a
            href="/lido-vault-solvency"
            className="underline underline-offset-3 hover:text-foreground transition-colors"
          >
            Lido V3 Vault Solvency Guarantee
          </a>
          {" "}. A formally verified property of a production smart contract.
        </p>
      </section>

      <footer className="mt-12 pt-8 border-t border-border">
        <p className="text-secondary text-sm">
          Part of the{" "}
          <a
            href="https://verity.labs"
            className="underline underline-offset-3 hover:text-foreground transition-colors"
          >
            Verity
          </a>{" "}
          benchmark initiative
        </p>
      </footer>
    </main>
  );
}
